// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProjApi.Data;

#nullable disable

namespace MiniProjApi.Migrations
{
    [DbContext(typeof(PostsContext))]
    partial class PostsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("MiniProjApi.Model.Posts", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownVotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UpVotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("MiniProjApi.Model.Posts", b =>
                {
                    b.OwnsMany("MiniProjApi.Model.Comments", "Comments", b1 =>
                        {
                            b1.Property<int>("CommentId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DownVotes")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PostId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PostId1")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("UpVotes")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CommentId");

                            b1.HasIndex("PostId");

                            b1.HasIndex("PostId1");

                            b1.ToTable("Comments");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.HasOne("MiniProjApi.Model.Posts", "Post")
                                .WithMany()
                                .HasForeignKey("PostId1")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Post");
                        });

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
